# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [48]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [49]:
np.__version__

'1.25.2'

#### 3. Create a null vector of size 10

In [50]:
vec=np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [51]:
print(vec.nbytes)

80


#### 5.  How to get the documentation of the numpy add function from the command line?

In [52]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [53]:
vec[4]=1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [54]:
my_arr=np.arange(10,50)
my_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [55]:
arr=np.array([1,2,3,4,5])

print(np.flip(arr))

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [56]:
mat=np.arange(9)
mat=mat.reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [57]:
indi=np.nonzero([1,2,0,0,4,0])
indi

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [58]:
iden=np.eye(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [59]:
ran=np.random.randn(3,3,3)
ran

array([[[-1.46084949e+00, -3.66494790e-01, -2.35682388e-01],
        [-7.28134991e-01, -1.02365824e+00, -6.42630357e-01],
        [ 1.14341424e+00, -1.24235269e+00, -5.24641768e-03]],

       [[-1.70730481e-01, -2.50275899e-01,  1.49588802e+00],
        [-2.42278927e+00, -1.44327717e+00,  1.09166218e+00],
        [ 8.50829623e-01, -2.04764893e+00, -9.17777603e-04]],

       [[ 1.17273130e+00, -1.26570013e+00,  3.41097071e-01],
        [ 9.88247541e-01,  7.90946912e-01,  1.07181255e+00],
        [ 2.77873771e-01, -1.12331129e+00,  4.49664272e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [61]:
ran=np.random.rand(10,10)
ran


array([[2.11081641e-01, 7.31436146e-01, 3.67878421e-02, 6.39410858e-01,
        6.19236195e-01, 6.08687354e-01, 7.51928033e-02, 5.08355619e-01,
        2.45352624e-02, 6.89714520e-01],
       [4.18641143e-01, 7.31111754e-01, 8.67177367e-01, 1.66579182e-01,
        4.74249547e-01, 4.29058887e-02, 6.20556173e-01, 7.11990691e-01,
        4.26515576e-01, 2.77932501e-01],
       [3.35940258e-01, 9.48969455e-01, 3.63427284e-01, 5.07377640e-01,
        8.61619286e-01, 1.70814907e-01, 1.44630108e-01, 4.00799645e-01,
        6.70360845e-01, 3.76673956e-01],
       [8.58585848e-01, 8.09095386e-01, 9.85961005e-01, 1.53379330e-01,
        1.95538530e-01, 7.93924326e-01, 7.49541705e-01, 1.11303381e-01,
        6.23464220e-01, 6.24000905e-01],
       [1.06093683e-01, 4.02358400e-02, 6.51905310e-01, 2.51522524e-02,
        8.57721308e-01, 6.26811723e-02, 8.98807051e-01, 7.42624352e-01,
        2.61224123e-01, 5.93126087e-01],
       [8.51585546e-01, 7.14306605e-01, 7.46599209e-01, 2.85566965e-01,
   

In [62]:
print(np.max(ran))
print(np.min(ran))

0.9859610047174222
0.0005359213887675685


#### 14. Create a random vector of size 30 and find the mean value

In [64]:
vector=np.random.rand(30)
print(np.mean(vector))

0.5239638545460122


#### 15. Create a 2d array with 1 on the border and 0 inside

In [67]:
rows=int(input())
cols=int(input())
onezero=np.zeros((rows,cols))
onezero[0,:]=1
onezero[-1,:]=1
onezero[:,0]=1
onezero[:,-1]=1
onezero

10
10


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [80]:
a=np.arange(1,10)
a=a.reshape(3,3)
a
r,c=a.shape

new_arr=np.zeros((r+2,c+2),dtype=a.dtype)
new_arr[1:-1,1:-1]=a
new_arr

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [82]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [83]:
from mmap import MAP_PRIVATE
val=[1,2,3,4]
mat=np.diag(val,k=-1)
mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [84]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1  # Odd rows, even columns
matrix[::2, 1::2] = 1  # Even rows, odd columns
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [87]:
shape=(6,7,8)
total_ele=np.prod(shape)
l_index=99
x=l_index//(shape[1]*shape[2])
remain=l_index%(shape[1]*shape[2])
y=remain//shape[2]
z=remain%shape[2]
print(x,y,z)
print(total_ele)

1 5 3
336
