In [ ]:
print("Hello")

Hello


In [ ]:
# !pip3 install numpy

# we are learning python machine learning

#### Numpy

In [ ]:
# !pip install pandas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
arr=np.array([[1,2,3]])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.ndim)

2


In [ ]:
print(arr.shape)

(1, 3)


In [ ]:
print(arr.dtype)

int32


In [ ]:
print(arr.size)

3


In [ ]:
print(arr)

[[1 2 3]]


In [ ]:
arr.shape

(1, 3)

In [ ]:
arr2=np.zeros((3,4))

In [ ]:
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a=np.full((3,3),6,dtype='complex')
print(a)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [ ]:
b=np.array((1,2,3))
b

array([1, 2, 3])

In [ ]:
ran=np.random.random((2,2))
print(ran)

[[0.89784396 0.65663572]
 [0.64450794 0.14680725]]


In [ ]:
o=np.ones((3,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
e=np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arrange=np.arange(1,19,2)
arrange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
p=np.linspace(2,19,20)
p

array([ 2.        ,  2.89473684,  3.78947368,  4.68421053,  5.57894737,
        6.47368421,  7.36842105,  8.26315789,  9.15789474, 10.05263158,
       10.94736842, 11.84210526, 12.73684211, 13.63157895, 14.52631579,
       15.42105263, 16.31578947, 17.21052632, 18.10526316, 19.        ])

In [ ]:
newarr=np.random.random((4,4))
newarr

array([[0.7921969 , 0.11052105, 0.85459292, 0.15956531],
       [0.98932062, 0.4552305 , 0.32364359, 0.32207115],
       [0.8979367 , 0.51165641, 0.19958446, 0.32765042],
       [0.5202559 , 0.95911807, 0.85131316, 0.06404676]])

In [ ]:
temp=newarr[1::2,:3:2]
temp

array([[0.98932062, 0.32364359],
       [0.5202559 , 0.85131316]])

In [ ]:
temp=np.array([[1,-2,2],[3,-1,3]])
cond=arr>0
new_temp=arr[cond]
new_temp

array([1, 2, 3])

In [ ]:
myarr=np.array([[1,2,3],[4,5,6]])
print(myarr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,0],[0,1]])
print(b)
print(a+b)
print(a*b)

[[1 0]
 [0 1]]
[[2 2]
 [3 5]]
[[1 0]
 [0 4]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a.vstack(b))

TypeError: vstack() takes 1 positional argument but 2 were given